name: KILDA apptainer deploy

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: debian-latest

    container:
        image: quay.io/singularity/singularity:v4.1.0
        options: --privileged

    steps:
    - uses: actions/checkout@v4
    - name: Build the Apptainer image
      run: |
        singularity build kiv2_20240530_0.2.sif kiv2_20240530.def
        singularity push kiv2_20240530_0.2.sif oras://ghcr.io/MCorentin/kilda:latest
